apiVersion: v1
data:
  config.yaml: |
    auth:
      admin:
        enabled: false
        existingSecret:
          key: admin-password
          name: ""
        username: admin
      oidc:
        admin_role: Admin
        auth_url: https://id.noosphere.uk/authorize
        client_id: garage-backup-ui
        cookie_http_only: true
        cookie_name: garage_backup_session
        cookie_same_site: lax
        cookie_secure: true
        email_attribute: email
        enabled: true
        existingSecret:
          key: client-secret
          name: garage-backup-ui-oidc-secret
        issuer_url: https://id.noosphere.uk
        name_attribute: name
        provider_name: id
        role_attribute_path: groups
        scopes:
        - openid
        - email
        - profile
        - groups
        session_max_age: 86400
        skip_expiry_check: false
        skip_issuer_check: false
        tls_skip_verify: false
        token_url: https://id.noosphere.uk/api/oidc/token
        userinfo_url: https://id.noosphere.uk/api/oidc/userinfo
        username_attribute: preferred_username
    cors:
      allow_credentials: false
      allowed_headers:
      - Origin
      - Content-Type
      - Accept
      - Authorization
      allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      allowed_origins:
      - https://ui.backup.garage.noosphere.uk
      enabled: true
      max_age: 3600
    garage:
      admin_endpoint: http://garage-backup-admin:3903
      endpoint: http://garage-backup-s3-api:3900
      existingSecret:
        key: admin-token
        name: garage-backup-admin-token
      region: backup
    logging:
      format: json
      level: info
    server:
      domain: ui.backup.garage.noosphere.uk
      environment: production
      host: 0.0.0.0
      max_body_size: 314572800
      max_header_size: 1048576
      port: 8080
      protocol: http
      read_buffer_size: 4096
      root_url: https://ui.backup.garage.noosphere.uk
      write_buffer_size: 4096
    serviceMonitor:
      enabled: true
      interval: 30s
      labels:
        prometheus: kube-prometheus
      path: /api/v1/monitoring/metrics
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: garage-backup-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garage-ui
    app.kubernetes.io/version: v0.4.2
    helm.sh/chart: garage-ui-0.2.5
  name: garage-backup-ui-config
  namespace: garage-operator
