apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: garage-backup-ui
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: garage-ui
    app.kubernetes.io/version: v0.11.1
    helm.sh/chart: garage-ui-0.11.1
  name: garage-backup-ui
  namespace: garage-operator
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: garage-backup-ui
    app.kubernetes.io/name: garage-ui
  type: ClusterIP
