apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-backup-ui-oidc-secret
  namespace: garage-operator
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSnFqQWNtWU50ZHBNMUNi
        bW1wd1Z5WTB5UzNEMU9hTEY2NHd4cHI5N1RnCno3Qm43NVNObE1WT0ozMHg0Qkk5
        d01GYTAxTDViUmEyZVBwbXBSNUZCckUKLS0tIG5YQVBibkM5M3NCakZ2bUpWM3RU
        OTRaTFNNZzdnVzFNcllLVGE0T29Ra28KoYrZEtVTf1qHwEIDZn9JpFpUqZ/Tv/sd
        hzucb6zh70xKh5ABzxqqlXnGK/oOB6XLVjMJXh1XgiuDinw5w5Qkzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-02-13T06:53:04Z"
  mac: ENC[AES256_GCM,data:WJcOKIWCyD7yYf4txvEpJJsUba5v9HhpmzobtXzMpD6VIiCfplxSqOiqmAlkBhbDcpmlftWB7aPYblBIwmKzadhQicAdOKwGv9rq5zFBPVYJgXVLaXXYdQ5sg4M+FLFqVc5MCzeu5drppwf5t62xYbsrU876+3GlWY17zgWIQGA=,iv:Vqtd/HihDzMEtsgpwU2tc8jKU1F4xT5vPMep8GXKhwI=,tag:GKI46H9KvAQIUPHnfyk+kw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:v66MPJdWPl/PDt+WUDsSJamW8jea82ldCUztsQ==,iv:5FKWyYf2Uvl1dBDL7O6IWxCDN6ZC0NqBJMCBUBOd6go=,tag:kAJ/WBRewKwkZ9DKY/oiiw==,type:str]
      stringData:
        client-secret: ENC[AES256_GCM,data:GEUyMjD+dwkrQq5+wjfX1PCDooDkmb2Ruj77WLCpT2k=,iv:nfG968KlPfpwv5hYi94z1CndExMtCukP286Kc1Ine3E=,tag:kTGqc9ko2+mjcZyTWWOUxg==,type:str]
      type: ENC[AES256_GCM,data:fEMrOzxo,iv:J1DQS8qD06OLBa3HW6gjVHiI7V7RsfaadeaqBPO++Ms=,tag:hlAkCblZB678kw6TyqdN2g==,type:str]
