apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-backup-ui-jwt-token-secret
  namespace: garage-operator
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVEVUS2czb1FaR2hjQWNF
        NHBNb2VFSnZVODNtU1RjNW5MK2h4Q3h4alVzCnFMWGlPYTRNNzFGcm8vWS9GSjJq
        OWNUTVJlRS9BcFVqdWwvdXlUQjIwV1kKLS0tIDNpdGxaUVhDeng5VmgvV0VLYkh2
        RFVTeUJDOE9HQ0F6cTVvYlJmMVozWVUKAK+fbC+QH8ymnXrnQHcLJ8zykJtv5BMO
        TeZht6VxRWQnTWNVHUXHLvLx5CsTXvgrNYk/9J+Tg7c9EpqYTt2ToQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-02-13T06:24:48Z"
  mac: ENC[AES256_GCM,data:j0x3y944VKoH7Q145tt/aOkppvTvzf7IIMHkUSpzTSoAgwENJuTOhegWYkIIRk0YkqN0WULHhU3lCQVD5Oiekw/1+Oc1ZbLqLShpXWw6+SN7WIN0S5LTUz68PwV0MshqwZPMzdjxOXwkSdmdMlDS6m/nIyLjcJR8ZccEgdX3fbc=,iv:tvH43SBsWJRNB0F9cTkCEloydH4HJBK7CSpsVh7mRSY=,tag:7TIX2dlwE7bjYoAAz8sLUw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:x8EBPi96c96tlG8v8PJyyjLkVfpmswZ7UBz08SB2EK3f,iv:ALVD6ESpK0FG+QczeRt5rluNr2jKm1G5fydtvm9jc1w=,tag:a626z2hhM7Lp71x6rkGptw==,type:str]
      stringData:
        jwt-key.pem: ""
      type: ENC[AES256_GCM,data:VTKkuZLS,iv:LORs8wAaRU+6GIfud5pE+pFzYBrk00tiLsv0BYNkL4o=,tag:FVMxv7mnL5dMu2en/iAXhQ==,type:str]
