apiVersion: v1
data:
  glance.yml: |
    server:
      assets-path: /app/assets
      proxied: true

    theme:
      # Note: assets are cached by the browser, changes to the CSS file
      # will not be reflected until the browser cache is cleared (Ctrl+F5)
      custom-css-file: /assets/user.css

    pages:
      # It's not necessary to create a new file for each page and include it, you can simply
      # put its contents here, though multiple pages are easier to manage when separated
      - $include: home.yml
      - $include: services.yml
  home.yml: |
    %YAML 1.1
    ---
    - columns:
      - size: small
        widgets:
        - first-day-of-the-week: monday
          type: calendar
        - cache: 12h
          collapse-after: 3
          feeds:
          - title: selfh.st
            url: https://selfh.st/rss/
          limit: 10
          type: rss
        - channels:
          - theprimeagen
          - christitustech
          type: twitch-channels
      - size: full
        widgets:
        - type: group
          widgets:
          - type: hacker-news
          - type: lobsters
        - channels:
          - UCXuqSBlHAE6Xw-yeJA0Tunw
          - UCR-DXc1voovS8nhAvccRZhg
          - UCsBjURrPoezykLs9EqgamOA
          - UCshObcm-nLhbu8MY50EZ5Ng
          - UC7rzjM9zAfOXRnXV8yKpgsg
          - UCoAVMy_9E_n75aZXbotfVjw
          - UCJa14zeVf8p6clixTOIOVyQ
          - UCylGUf9BvQooEFjgdNudoQg
          collapse-after-rows: 2
          style: horizontal-cards
          type: videos
        - type: group
          widgets:
          - subreddit: nixos
            type: reddit
          - subreddit: linux
            type: reddit
          - subreddit: rust
            type: reddit
          - subreddit: kubernetes
            type: reddit
          - subreddit: selfhosted
            type: reddit
          - subreddit: homelab
            type: reddit
          - subreddit: technology
            type: reddit
          - subreddit: unixporn
            type: reddit
      - size: small
        widgets:
        - cache: 1d
          repositories:
          - immich-app/immich
          - codeberg:forgejo/forgejo
          - karakeep-app/karakeep
          - glanceapp/glance
          - lukasdietrich/glance-k8s
          - dockerhub:seerr/seerr
          - arnarg/nixidy
          - nix-community/nixhelm
          - cloudnative-pg/cloudnative-pg
          - kubernetes-csi/csi-driver-nfs
          - gitlab:TECHNOFAB/tofunix
          show-source-icon: true
          title: Git
          type: releases
        - cache: 1d
          repositories:
          - adyxax/terraform-provider-forgejo
          - carlpett/terraform-provider-sops
          - goharbor/terraform-provider-harbor
          show-source-icon: true
          title: Open Tofu Providers
          type: releases
      name: Home
  services.yml: "%YAML 1.1\n---\n- center-vertically: true\n  columns:\n  - size: full\n    widgets:\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      title: Nodes\n      type: extension\n      url: http://glance-k8s/extension/nodes\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\n (\\\"category\\\" in annotations && annotations[\\\"category\\\"] == \\\"gitops\\\"\\\n          )\\n\"\n      title: GitOps\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\nannotations[\\\"glance/hide\\\"] != \\\"true\\\" and\\n(\\\"category\\\" in annotations\n          && annotations[\\\"category\\\"] == \\\"storage\\\")\\n\"\n      title: Storage\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\n (\\\"category\\\" in annotations && annotations[\\\"category\\\"] == \\\"monitoring\\\"\\\n          )\\n\"\n      title: Monitoring\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\n (\\\"category\\\" in annotations && annotations[\\\"category\\\"] == \\\"yarr\\\"\\\n          )\\n\"\n      title: Yarr\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\n (\\\"category\\\" in annotations && annotations[\\\"category\\\"] == \\\"security\\\"\\\n          )\\n\"\n      title: Security\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\n (\\\"category\\\" in annotations && annotations[\\\"category\\\"] == \\\"search\\\"\\\n          )\\n\"\n      title: Search\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\n (\\\"category\\\" in annotations && annotations[\\\"category\\\"] == \\\"productivity\\\"\\\n          )\\n\"\n      title: Productivity\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - allow-potentially-dangerous-html: true\n      cache: 1m\n      parameters:\n        show-if: \"namespace != \\\"kube-system\\\" and\\n\\\"glance/name\\\" in annotations\n          and\\n (\\\"category\\\" in annotations && annotations[\\\"category\\\"] == \\\"utils\\\"\\\n          )\\n\"\n      title: Utils\n      type: extension\n      url: http://glance-k8s/extension/apps\n    - groups:\n      - hide-arrow: true\n        links:\n        - icon: https://nixidy.dev/logo.svg\n          title: Nixidy\n          url: https://nixidy.dev/\n        - icon: di:artifacthub\n          title: Artifact Hub\n          url: https://artifacthub.io/\n        - icon: di:artifacthub\n          title: Operator Hub\n          url: https://operatorhub.io/\n        title: K8s\n      - hide-arrow: true\n        links:\n        - icon: sh:postgresql\n          title: CloudNative PG\n          url: https://cloudnative-pg.io/docs/\n        - icon: sh:postgresql\n          title: CloudNative PG Examples\n          url: \n            https://github.com/cloudnative-pg/cloudnative-pg/tree/main/docs/src/samples\n        - icon: sh:postgresql\n          title: Barman Cloud Plugin\n          url: https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/\n        - icon: di:argo-cd\n          title: Argo CD\n          url: https://argo-cd.readthedocs.io/en/stable/\n        - icon: di:longhorn\n          title: Longhorn\n          url: https://longhorn.io/docs\n        title: Docs\n      - hide-arrow: true\n        links:\n        - icon: di:nixos\n          title: Nix Wiki\n          url: https://wiki.nixos.org/wiki/NixOS_Wiki\n        - icon: di:nixos\n          title: Noogle\n          url: https://noogle.dev\n        - icon: di:nixos\n          title: Nixos Search\n          url: https://search.nixos.org/packages\n        - icon: auto-invert \n            https://docs.clan.lol/main/static/icons/clan-logo.svg\n          title: Clan.lol\n          url: https://docs.clan.lol\n        title: Nix\n      - hide-arrow: true\n        links:\n        - icon: https://external-content.duckduckgo.com/ip3/deepwiki.org.ico\n          title: Deep Wiki\n          url: https://deepwiki.org/\n        title: Utils\n      - hide-arrow: true\n        links:\n        - icon: mdi:material-ui\n          title: Material Design Icons\n          url: https://pictogrammers.com/library/mdi/\n        - icon: di:dashboard-icons\n          title: Dashboard Icons\n          url: https://dashboardicons.com/icons\n        - icon: sh:selfh-st\n          title: Selfh.st Icons\n          url: https://selfh.st/icons/\n        title: Icons\n      type: bookmarks\n    width: slim\n  name: Services\n  width: slim\n"
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
