apiVersion: v1
data:
  glance.yml: |
    server:
      assets-path: /app/assets
      proxied: true

    theme:
      # Note: assets are cached by the browser, changes to the CSS file
      # will not be reflected until the browser cache is cleared (Ctrl+F5)
      custom-css-file: /assets/user.css

    pages:
      # It's not necessary to create a new file for each page and include it, you can simply
      # put its contents here, though multiple pages are easier to manage when separated
      - $include: home.yml
      - $include: services.yml
  home.yml: |
    - columns:
      - size: small
        widgets:
        - first-day-of-the-week: monday
          type: calendar
        - cache: 12h
          collapse-after: 3
          feeds:
          - title: selfh.st
            url: https://selfh.st/rss/
          limit: 10
          type: rss
        - channels:
          - theprimeagen
          - christitustech
          type: twitch-channels
      - size: full
        widgets:
        - type: group
          widgets:
          - type: hacker-news
          - type: lobsters
        - channels:
          - UCXuqSBlHAE6Xw-yeJA0Tunw
          - UCR-DXc1voovS8nhAvccRZhg
          - UCsBjURrPoezykLs9EqgamOA
          - UCshObcm-nLhbu8MY50EZ5Ng
          - UC7rzjM9zAfOXRnXV8yKpgsg
          - UCoAVMy_9E_n75aZXbotfVjw
          - UCJa14zeVf8p6clixTOIOVyQ
          - UCylGUf9BvQooEFjgdNudoQg
          collapse-after-rows: 2
          style: horizontal-cards
          type: videos
        - type: group
          widgets:
          - subreddit: nixos
            type: reddit
          - subreddit: linux
            type: reddit
          - subreddit: rust
            type: reddit
          - subreddit: kubernetes
            type: reddit
          - subreddit: selfhosted
            type: reddit
          - subreddit: homelab
            type: reddit
          - subreddit: technology
            type: reddit
          - subreddit: unixporn
            type: reddit
      - size: small
        widgets:
        - cache: 1d
          repositories:
          - immich-app/immich
          - codeberg:forgejo/forgejo
          - karakeep-app/karakeep
          - glanceapp/glance
          - lukasdietrich/glance-k8s
          - dockerhub:seerr/seerr
          - arnarg/nixidy
          - nix-community/nixhelm
          - cloudnative-pg/cloudnative-pg
          - kubernetes-csi/csi-driver-nfs
          show-source-icon: true
          type: releases
      name: Home
  services.yml: |
    - center-vertically: true
      columns:
      - size: full
        widgets:
        - allow-potentially-dangerous-html: true
          cache: 1m
          title: Nodes
          type: extension
          url: http://glance-k8s/extension/nodes
        - allow-potentially-dangerous-html: true
          cache: 1m
          parameters:
            show-if: "namespace != \"kube-system\" and\n\"glance/name\" in annotations\
              \ and\n (\"category\" in annotations && annotations[\"category\"] == \"\
              gitops\")\n"
          title: GitOps
          type: extension
          url: http://glance-k8s/extension/apps
        - allow-potentially-dangerous-html: true
          cache: 1m
          parameters:
            show-if: 'namespace != "kube-system" and

              "glance/name" in annotations and

              annotations["glance/hide"] != "true" and

              ("category" in annotations && annotations["category"] == "storage")

              '
          title: Storage
          type: extension
          url: http://glance-k8s/extension/apps
        - allow-potentially-dangerous-html: true
          cache: 1m
          parameters:
            show-if: "namespace != \"kube-system\" and\n\"glance/name\" in annotations\
              \ and\n (\"category\" in annotations && annotations[\"category\"] == \"\
              monitoring\")\n"
          title: Monitoring
          type: extension
          url: http://glance-k8s/extension/apps
        - allow-potentially-dangerous-html: true
          cache: 1m
          parameters:
            show-if: "namespace != \"kube-system\" and\n\"glance/name\" in annotations\
              \ and\n (\"category\" in annotations && annotations[\"category\"] == \"\
              yarr\")\n"
          title: Yarr
          type: extension
          url: http://glance-k8s/extension/apps
        - allow-potentially-dangerous-html: true
          cache: 1m
          parameters:
            show-if: "namespace != \"kube-system\" and\n\"glance/name\" in annotations\
              \ and\n (\"category\" in annotations && annotations[\"category\"] == \"\
              security\")\n"
          title: Security
          type: extension
          url: http://glance-k8s/extension/apps
        - allow-potentially-dangerous-html: true
          cache: 1m
          parameters:
            show-if: "namespace != \"kube-system\" and\n\"glance/name\" in annotations\
              \ and\n (\"category\" in annotations && annotations[\"category\"] == \"\
              utils\")\n"
          title: Utils
          type: extension
          url: http://glance-k8s/extension/apps
        - groups:
          - hide-arrow: true
            links:
            - icon: https://nixidy.dev/logo.svg
              title: Nixidy
              url: https://nixidy.dev/
            - icon: di:artifacthub
              title: Artifact Hub
              url: https://artifacthub.io/
            - icon: di:artifacthub
              title: Operator Hub
              url: https://operatorhub.io/
            title: K8s
          - hide-arrow: true
            links:
            - icon: sh:postgresql
              title: Cloud Native PG
              url: https://cloudnative-pg.io/docs/
            - icon: sh:postgresql
              title: Cloud Native PG Examples
              url: https://github.com/cloudnative-pg/cloudnative-pg/tree/main/docs/src/samples
            - icon: sh:postgresql
              title: Barman Cloud Plugin
              url: https://cloudnative-pg.io/plugin-barman-cloud/docs/usage/
            - icon: di:argo-cd
              title: Argo CD
              url: https://argo-cd.readthedocs.io/en/stable/
            - icon: di:longhorn
              title: Longhorn
              url: https://longhorn.io/docs
            title: Docs
          - hide-arrow: true
            links:
            - icon: di:nixos
              title: Nix Wiki
              url: https://wiki.nixos.org/wiki/NixOS_Wiki
            - icon: di:nixos
              title: Noogle
              url: https://operatorhub.io/
            - icon: di:nixos
              title: Nixos Search
              url: https://search.nixos.org/packages
            - icon: auto-invert https://docs.clan.lol/main/static/icons/clan-logo.svg
              title: Clan.lol
              url: https://docs.clan.lol
            title: Nix
          - hide-arrow: true
            links:
            - icon: https://external-content.duckduckgo.com/ip3/deepwiki.org.ico
              title: Deep Wiki
              url: https://deepwiki.org/
            title: Utils
          - hide-arrow: true
            links:
            - icon: mdi:material-ui
              title: Material Design Icons
              url: https://pictogrammers.com/library/mdi/
            - icon: di:dashboard-icons
              title: Dashboard Icons
              url: https://dashboardicons.com/icons
            - icon: sh:selfh-st
              title: Selfh.st Icons
              url: https://selfh.st/icons/
            title: Icons
          type: bookmarks
        width: slim
      name: Services
      width: slim
kind: ConfigMap
metadata:
  name: glance-config
  namespace: glance
