apiVersion: v1
data:
  garage.toml: "metadata_dir = \"/mnt/meta\"\ndata_dir = \"/mnt/data\"\n\ndb_engine = \"lmdb\"\n\nblock_size = \"1048576\"\n\nreplication_factor = 3\nconsistency_mode = \"consistent\"\n\ncompression_level = 1\n\nrpc_bind_addr = \"[::]:3901\"\n# rpc_secret will be populated by the init container from a k8s secret object\nrpc_secret = \"__RPC_SECRET_REPLACE__\"\n\nbootstrap_peers = [ \n]\n\n[kubernetes_discovery]\nnamespace = \"garage\"\nservice_name = \"garage\"\nskip_crd = false\n\n[s3_api]\ns3_region = \"garage\"\napi_bind_addr = \"[::]:3900\"\nroot_domain = \".s3.garage.tld\"\n\n[s3_web]\nbind_addr = \"[::]:3902\"\nroot_domain = \".web.garage.tld\"\nindex = \"index.html\"\n\n[admin]\napi_bind_addr = \"[::]:3903\""
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage
