apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pg-radarr-password
  namespace: yarr
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaTZzaER3MmV6R0M4OFc0
        VnY2Nm85RHNMWC8yaHdwRjlVZm5LQUpoWFVvClducWRCZndCYXlXZytlY2Fob2NF
        NW4xWWQ4MS84dC9UTWIzNHJuSjJUTlkKLS0tICtKei8wQjN6eEo1L0F0N01POTg4
        UzQ1L1NPSk83OVRpajJ6U2xDUVZmTmMKUIWE+t65XxfItUj+PuS8Akh/xCT4/gNA
        igBPllSRPZ3qsuGFTNPMF0tp3YXl6JZTL/ydamoY8403jbl1V2bhOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-02-28T18:58:16Z"
  mac: ENC[AES256_GCM,data:Uu/b0CeCwCvZ/MXIJlXh5E6dQnWfmoasZl3CAnfWXXxCwQRSr29fbINgBFGwizkmsZc7p/07fH3tF82BmVcFCEbuly7gH0HnhG5WzAe91juwijdcqEkuuJG9kRqQYWdHzy3HnbIKbiBLVNKAdJmn+4J2w5G5qfFf+sX1alvhbsc=,iv:rNgCVvRXRhsuYnbJWdbAb0fabdBT3/Tzdec6ywOeM1w=,tag:NTKc6L3/S0lF9vprbqiWZg==,type:str]
  version: 3.12.0
spec:
  secretTemplates:
    - labels:
        cnpg.io/reload: ENC[AES256_GCM,data:fislpQ==,iv:/PGV9dSNdJkHdolQxVREqyRErItzDF5/H85XAAMl4Zg=,tag:n2JEfT6YZi4fsSPZ6Tc3BA==,type:str]
      name: ENC[AES256_GCM,data:/JbjFDoVD/omX21Px9lVVCB3,iv:kAwdGAEEEUcb5hkcwGgos0XsugNGbn7WAXN4MviA3sM=,tag:o+Z5aJzag6KeuB+UWCTddg==,type:str]
      stringData:
        password: ENC[AES256_GCM,data:oDkeM8Vx2wODiZ9As3wrD9iij4M=,iv:a+5xu6zlRQphp6VwjjpPT3ygBloRE5oyZCzxJnzX2aM=,tag:lN04sj4NO9vpBUVgHUV4AQ==,type:str]
        username: ENC[AES256_GCM,data:dxQUEIkL,iv:2V6Ohx9qjO0tXzc/Jj+5gCT5H16mOzaARPeK90YODC0=,tag:2WT0aA0xpZnNrK8mgIWEkA==,type:str]
      type: ENC[AES256_GCM,data:Vo5DdNYO,iv:OANd97FeHUrxVHEwGjN5hDiUwwxa4WlWKay69R2wbMs=,tag:U1pOWS9TwzkvFvPdMRii9Q==,type:str]
