apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: keycloak
  namespace: garage-operator
spec:
  bucketPermissions:
    - bucketRef:
        name: keycloak
      owner: true
      read: true
      write: true
  clusterRef:
    name: garage-backup
  secretTemplate:
    accessKeyIdKey: MINIO_ACCESS_KEY_ID
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: keycloak
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: keycloak
    name: keycloak-s3-secret-key
    secretAccessKeyKey: MINIO_SECRET_ACCESS_KEY
