apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: harbor
  namespace: garage-operator
spec:
  clusterRef:
    name: garage-main
  keyPermissions:
    - keyRef: harbor
      owner: true
      read: true
      write: true
