apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: pocket-id
  namespace: garage-operator
spec:
  clusterRef:
    name: garage-backup
  keyPermissions:
    - keyRef: pocket-id
      owner: true
      read: true
      write: true
