apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageCluster
metadata:
  name: garage-main
  namespace: garage-operator
spec:
  admin:
    adminTokenSecretRef:
      key: admin-token
      name: garage-main-admin-token
    enabled: true
  database:
    engine: sqlite
  discovery:
    kubernetes:
      enabled: true
  layoutManagement:
    autoApply: true
    minNodesHealthy: 2
  layoutPolicy: Auto
  network:
    rpcSecretRef:
      key: rpc-secret
      name: garage-main-rpc-secret
  replicas: 3
  replication:
    factor: 3
  s3Api:
    bindPort: 3900
    region: main
    rootDomain: .s3.main.garage.noosphere.uk
  storage:
    data:
      size: 200Gi
      storageClassName: local-path
    metadata:
      size: 10Gi
      storageClassName: local-path
  zone: main
