apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: garage-main-admin-token
  namespace: garage-operator
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Rm5XdWI1SGJTMTBWeXlJ
        czBEMndMVDJJSmRFMTlGa3JPRFppeCs3ZVNJCk5DNFprbTZ0NW9ZS05BaXU1Vm1N
        SHJSaFR5SFRya0NaV2RTbFVLNTFteHMKLS0tIFlzQ21oZWswLzZlY1BGc25VMXpm
        bEU1RFlEWHdXTUFVSjZEd1BScjNrQmsKC6nMRrncixMzV84rpM+lvXnx4IJhkTiH
        baw5LgTJYr3ebMdlmgPl+FVNDB3yXKW/oeA8zyRYLgms8p7/lU22yA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-02-11T13:28:37Z"
  mac: ENC[AES256_GCM,data:lvbhmz780zxU07zyle+LR8iEqu+8vyWSEg52mlMgu0wmhRmUCttCu2MrVbuUUdrHmlWvRKI5K9RxW88oGQN9xJU2ZjqTGv4hOJubYDXG0inqBcGmBiTvCWOqx9iG8GxEHs2KFUYFW0h+hcV/raavc40gn2gSP1MX5CTWMhswDJE=,iv:jObOXq6QK09BfSwiCbCWOkMjEsjI4FQZF51JKJwEKsg=,tag:EyQ53TVZF6YYf2eMwZ7c3g==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:ku9sfanWH1FBoSMU9ZcLXy/oiOZ4XHw=,iv:n4eLsGcGfNUe4DlM8dNthVRdk1Ij0ht7W0W6IqOPK5A=,tag:JUhdF7qKavNpzigaPH8wUg==,type:str]
      stringData:
        admin-token: ENC[AES256_GCM,data:/dFwjL9mByrmUDwN1i2Ibdgvlhpi6FGf/lMvzfyux7mvow1H3B5G56ZkQsBbtKkTWxO1+0+SBNPYc+lBzeuo+w==,iv:4eh1i/tIk+NlaBfqh5Upq+qD1MrgUv/Z9ROhu/464l4=,tag:Hds/Rn+1Rwlw8gAETebR9Q==,type:str]
      type: ENC[AES256_GCM,data:whs/bkdH,iv:0P/sI6BJIkCeuwq7673Ikjxl2MNMKZKFG4VB2C4y8DE=,tag:WiVMMflced+jgkphOa324w==,type:str]
