apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: unifi-mongodb
  namespace: unifi
spec:
  additionalMongodConfig:
    net.tls.mode: disabled
    storage.wiredTiger.engineConfig.journalCompressor: snappy
  members: 3
  security:
    authentication:
      modes:
        - SCRAM
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: longhorn
        - metadata:
            name: logs-volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: longhorn
  type: ReplicaSet
  users:
    - db: unifi
      name: unifi
      passwordSecretRef:
        key: password
        name: unifi-mongodb-password
      roles:
        - db: unifi
          name: dbOwner
        - db: admin
          name: clusterMonitor
      scramCredentialsSecretName: unifi-mongodb-scram
  version: 7.0.12
