apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: unifi-s3-secret-key
  namespace: unifi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ0E3UEhmdFo2RllqRmhY
        TlNyQkhPME5WYUNJamlKemhrNFk5dlNjOEZBCk9QdWdXTG9GQjQvTnJtcVZnVTh4
        RlZPQ0pObGxFQ0N6R3gxV3lkeGxXTmMKLS0tIEM5aXE0UFhzaWxVektNbTlZTVdQ
        K2RLdzhLZFhEemM4dTU1NGdqUWlZeTAKxtO6L94b2LyYM7/mHERIMtZQXEwkaRSW
        6I6fDK1IsFOnXK+vhMBqywLnp3B0e5MA81rzFm1qYeQoEp0KJPf3Sw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-15T18:09:37Z"
  mac: ENC[AES256_GCM,data:4K9jM6g/atv4lBkdYM9sSK0ytdl5eDsKmd/AD2GS0HD0MsTkK1G19fIpGtz/tlI2wzJj4IEcvy0q2bCwrXFS1aKZxWEDz1gNuL5RQCadXe7GnD+zsqPd1cy2lGNtWLKs6FhP5uuPTO8QOkyM45kEqUxVX6RiCfjFEM2aFCOuoME=,iv:QmigU0fGwvt5M87Qisny9M39MFJtGKFApcci6T2qCgg=,tag:uVdmXo87VEnmRF3/IGO8+g==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:MWYOCaxrQ5g9p0OJek7iyHRn1A==,iv:9B6hnjEgq0wdKFS+KLGSUB22S5cW526ZAUFKrNn2Ckk=,tag:1U/14lMedwLEBJ2W0rRVCQ==,type:str]
      stringData:
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LxjPCVHY4K5ATtkAJBp6dzNROfRDv2cChMI=,iv:pYgqDsZlWU56M54H8433NfaxUaXvIQ9VWh2dyGkrVBM=,tag:29Q+rQ8CGk/xcOcS02d/rg==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:JjDzzlczhHkmTqqWRT1l7G7T8lmAVErO3lMwtViFjJuVI0DhRaofyq2qViLEET3MPKBuHHUkTlkNNSIgGSvVbw==,iv:a97MnB0raTHCSGQZ1YpMSw41epzAZ6FehS35HzbZWJY=,tag:9DFZZYV4YYbeOkz/VQlZtg==,type:str]
      type: ENC[AES256_GCM,data:zBNc/iYw,iv:AobmZ8Tx8vlGuZvcyTO/XB9+8bVYTGpHWsrNYVYCpKU=,tag:OdjtM7gpFcCnc8YoxyE7zQ==,type:str]
