# Kaneo — self-hosted project/task tracker. Upstream ships a compose.yml with a
# bundled postgres:16-alpine and an optional MinIO; neither is needed here.
# Cerberus already runs Postgres (stc/server.nix) and the k8s cluster already
# runs Garage, so the whole compose file collapses to this one container.
#
# Reachable at https://kaneo.<lab-domain> via Caddy on the LAN/VPN only —
# deliberately NOT added to the Pangolin blueprint in ./configuration.nix.
{
  self,
  config,
  lib,
  pkgs,
  ...
}: let
  inherit (self.lib) mkRevProxyVHost mkDomain;

  port = 5173;

  # The stored var keeps a trailing newline (caddy.nix writes it with `echo`),
  # which would corrupt the env file line. Caddy gets the {$LAB_DOMAIN} runtime
  # placeholder via mkDomain; Kaneo needs the literal value.
  baseDomain = lib.removeSuffix "\n" config.clan.core.vars.generators."caddy-env".files."domain".value;
  clientUrl = "https://kaneo.${baseDomain}";

  # garage-main, reached over its Traefik ingress. Must be the PUBLIC hostname,
  # not the in-cluster Service: Kaneo hands out presigned URLs that the browser
  # itself uploads to. Technitium resolves this to the MetalLB VIP 192.168.1.251
  # directly, so it does not hairpin through this machine's Caddy.
  s3Endpoint = "https://s3.main.garage.noosphere.uk";
  s3Bucket = "kaneo";
  s3Region = "main";

  s3EnvFile = config.clan.core.vars.generators."kaneo-s3-key".files."kaneo-s3.env".path;

  # Uploads are presigned PUTs issued to the browser, so the bucket must allow
  # Kaneo's origin. The GarageBucket CRD has no CORS field, so it is applied
  # over the S3 API instead (Garage implements PutBucketCors).
  corsConfig = pkgs.writeText "kaneo-cors.json" (builtins.toJSON {
    CORSRules = [
      {
        AllowedHeaders = ["*"];
        AllowedMethods = ["GET" "PUT" "HEAD"];
        AllowedOrigins = [clientUrl];
        ExposeHeaders = ["ETag"];
        MaxAgeSeconds = 3000;
      }
    ];
  });
in {
  # Database. The password is generated by the kaneo-secrets generator below and
  # handed to Postgres via passwordDependency, so the two can never drift.
  # This also enrols `kaneo` in the nightly pg_dump (backup.databases defaults
  # to every managed database).
  services.imperium.postgresql.users.kaneo = {
    databases = ["kaneo"];
    ensureDBOwnership = true;
    passwordDependency = "kaneo-secrets";
  };

  # Auto-generated, no prompts: the DB password (also consumed by Postgres via
  # the `password` file) and the JWT signing secret. Hex only — a password
  # containing @ / % breaks DATABASE_URL parsing.
  clan.core.vars.generators.kaneo-secrets = {
    files."password" = {secret = true;};
    files."kaneo.env" = {
      secret = true;
      mode = "0400";
    };
    runtimeInputs = with pkgs; [coreutils openssl];
    script = ''
      DB_PASSWORD="$(openssl rand -hex 24)"
      AUTH_SECRET="$(openssl rand -hex 32)"
      printf '%s' "$DB_PASSWORD" > "$out/password"
      cat > "$out/kaneo.env" <<EOF
      DATABASE_URL=postgresql://kaneo:$DB_PASSWORD@127.0.0.1:5432/kaneo
      AUTH_SECRET=$AUTH_SECRET
      EOF
    '';
  };

  virtualisation.oci-containers.containers.kaneo = {
    image = "ghcr.io/usekaneo/kaneo:latest";
    autoStart = true;
    # Host networking so the container reaches Postgres on 127.0.0.1:5432 — the
    # podman bridge (10.88.0.0/16) is not in pg_hba.conf, which only allows
    # 127.0.0.1/32 and 192.168.1.0/24. Port 5173 is not in the firewall
    # allow-list (stc/server.nix), so this stays local to the host.
    extraOptions = ["--network=host"];
    environment = {
      KANEO_CLIENT_URL = clientUrl;
      # KANEO_API_URL is intentionally unset: it defaults to
      # KANEO_CLIENT_URL + /api and the merged image proxies /api internally.

      S3_ENDPOINT = s3Endpoint;
      S3_BUCKET = s3Bucket;
      S3_REGION = s3Region;
      S3_FORCE_PATH_STYLE = "true";

      # Same workaround the cluster applies for Garage in
      # _modules/templates/garage-object-store.nix — modern AWS SDKs send
      # checksum trailers Garage rejects. The JS SDK v3 honours these.
      AWS_REQUEST_CHECKSUM_CALCULATION = "when_required";
      AWS_RESPONSE_CHECKSUM_VALIDATION = "when_required";

      # Anonymous sign-in is on by default upstream; drop this line to allow it.
      # Registration stays open so the first account can be created — flip
      # DISABLE_REGISTRATION=true afterwards.
      DISABLE_GUEST_ACCESS = "true";

      # The Gitea/Forgejo integration routes every outbound API call through
      # assertPublicDestination(), which resolves the base URL and rejects any
      # answer in 10/8, 172.16/12, 192.168/16, 127/8 — or the literal hostname
      # "localhost". forge.ugalabugala.org resolves to 192.168.1.105 on the LAN,
      # so the integration dies with "Invalid Gitea token or could not reach
      # instance." before a single request leaves the container. This flag is
      # upstream's escape hatch. It re-opens the SSRF surface that check guards,
      # which is acceptable here: Kaneo is LAN/VPN-only and only authenticated
      # workspace admins can set an integration URL.
      KANEO_ALLOW_PRIVATE_WEBHOOK_DESTINATIONS = "true";
    };
    environmentFiles = [
      config.clan.core.vars.generators.kaneo-secrets.files."kaneo.env".path
      s3EnvFile
    ];
    labels."io.containers.autoupdate" = "registry";
  };

  # Apply the bucket CORS policy before the app starts. PutBucketCors is
  # idempotent, so re-running on every boot is safe and self-healing.
  systemd.services.kaneo-s3-cors = {
    description = "Apply CORS policy to the Kaneo Garage bucket";
    after = ["network-online.target"];
    wants = ["network-online.target"];
    before = ["podman-kaneo.service"];
    wantedBy = ["podman-kaneo.service"];
    path = [pkgs.awscli2];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      EnvironmentFile = s3EnvFile;
      # The bucket is created by garage-operator on the cluster; if ArgoCD has
      # not synced yet, retry rather than leaving the app without CORS.
      Restart = "on-failure";
      RestartSec = "30s";
    };
    environment.AWS_REGION = s3Region;
    environment.AWS_REQUEST_CHECKSUM_CALCULATION = "when_required";
    environment.AWS_RESPONSE_CHECKSUM_VALIDATION = "when_required";
    script = ''
      aws --endpoint-url ${s3Endpoint} s3api put-bucket-cors \
        --bucket ${s3Bucket} \
        --cors-configuration "file://${corsConfig}"
    '';
  };

  # https://kaneo.<lab-domain> -> the container. LAN/VPN only.
  services.caddy.virtualHosts."${mkDomain "kaneo"}".extraConfig =
    mkRevProxyVHost {inherit port;};
}
