# nopresh — self-hosted medication/health tracker. Single OCI image (Go binary
# with the SPA embedded) served on :5000, deployed as a podman container. CI
# (Forgejo Actions, see ./forgejo-runner.nix) pushes :latest to the Forgejo
# registry; podman-auto-update pulls new images automatically.
{
  self,
  config,
  pkgs,
  ...
}: let
  inherit (self.lib) mkRevProxyVHost mkDomain;
  port = 5000;
in {
  # First container host in the fleet — enable podman.
  imports = [self.nixosModules.virtualisation];
  services.imperium.virtualisation.podman.enable = true;

  # Forgejo (and its container registry) run on THIS machine. Public DNS points
  # forge.ugalabugala.org at the VPS, so pulling/pushing would hairpin out to the
  # internet and back through Pangolin (which doesn't proxy the registry cleanly).
  # Resolve it locally -> Caddy -> Forgejo instead.
  networking.hosts."192.168.1.105" = ["forge.ugalabugala.org"];

  # Database. The password is generated by the nopresh-secrets generator below
  # (via passwordDependency) and shared with the container's env file, so there
  # is no prompt and the two always match.
  services.imperium.postgresql.users.nopresh = {
    databases = ["nopresh"];
    ensureDBOwnership = true;
    passwordDependency = "nopresh-secrets";
  };

  # Auto-generated secrets (no prompts): a random DB password (also consumed by
  # Postgres via the `password` file) and a random JWT secret, written into the
  # env file the container reads.
  clan.core.vars.generators.nopresh-secrets = {
    files."password" = {secret = true;};
    files."nopresh.env" = {
      secret = true;
      mode = "0400";
    };
    runtimeInputs = with pkgs; [coreutils openssl];
    script = ''
      DB_PASSWORD="$(openssl rand -hex 24)"
      JWT_SECRET_KEY="$(openssl rand -hex 32)"
      printf '%s' "$DB_PASSWORD" > "$out/password"
      cat > "$out/nopresh.env" <<EOF
      DB_PASSWORD=$DB_PASSWORD
      JWT_SECRET_KEY=$JWT_SECRET_KEY
      EOF
    '';
  };

  virtualisation.oci-containers.backend = "podman";
  virtualisation.oci-containers.containers.nopresh = {
    image = "forge.ugalabugala.org/manjo/nopresh:latest";
    autoStart = true;
    # host networking so the container reaches Postgres on 127.0.0.1:5432, and
    # binds the app to loopback only (Caddy fronts it). HOST overrides the
    # image's baked 0.0.0.0.
    extraOptions = ["--network=host"];
    environment = {
      HOST = "127.0.0.1";
      PORT = toString port;
      DB_HOST = "127.0.0.1";
      DB_PORT = "5432";
      DB_USER = "nopresh";
      DB_NAME = "nopresh";
    };
    environmentFiles = [
      config.clan.core.vars.generators.nopresh-secrets.files."nopresh.env".path
    ];
    labels."io.containers.autoupdate" = "registry";
  };

  # https://nopresh.<lab-domain> -> the container.
  services.caddy.virtualHosts."${mkDomain "nopresh"}".extraConfig =
    mkRevProxyVHost {inherit port;};

  # CD: pull a new :latest daily and restart (keeps the previous image so
  # `podman auto-update --rollback` can revert a bad build).
  systemd.services.podman-auto-update = {
    description = "Podman auto-update";
    after = ["network-online.target" "podman.service"];
    wants = ["network-online.target"];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${config.virtualisation.podman.package}/bin/podman auto-update";
    };
  };
  systemd.timers.podman-auto-update = {
    wantedBy = ["timers.target"];
    timerConfig = {
      OnCalendar = "daily";
      Persistent = true;
    };
  };
}
