apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: karakeep-zitadel-secret
  namespace: karakeep
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S1VQbTJkR2FBblU1dy8w
        SXg1Y3dvWkkzUFMzc1F1YjUwdktvOFB1SnhZCnJrUlEzaGZySEg2K1QvOUI2OFg3
        TFRsOCs0TXdmcjFRZHM5eE9YQ3ZIZFUKLS0tIEpyWGF0YWFNdGNka3dDMVhKS3Bh
        NVFBbGpPbWdZWkJLWDhWb3dlRERQOVUKvz6/s+YMQNkIsOgVqNIo9Cl59J5fkynh
        HKelSOTXEl5Qnf5up8Vw6S3GiRMV3GlFXdp8v0sN5N0Yl89F9jVnMQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-06T15:19:09Z"
  mac: ENC[AES256_GCM,data:FhttZci6OVhDUIJs3zzuzj8sGiWAX043KeQkkn+l4HCPT+HOW2lg2QjrjUI7budFDhll+GWZevWtpD3K/yDp02O6F4ze2EGIVWtfoLZ/cDG26tiL8AH3CNBJST6BwNlqWXCXiFQwaam+QqcDm/WH0PPG38WSs1fCQVvSZFK9fvo=,iv:WS6jPlrbKNSpqHEYXo3qGjxeWmHzMer7+uWS+3vMtBI=,tag:oFYLA3uPrHYxxGIyjV9AMw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:DYdQbAzZ5UUzmcegPELuRXZrpVNf0NI=,iv:fbMzlPShZYvYb/E6wRpnUKz6X00zknIY9PkqjwcbGsM=,tag:G0BAN2OtnuIfO0v2ybCqMA==,type:str]
      stringData:
        OAUTH_CLIENT_ID: ENC[AES256_GCM,data:DqDNha7O+KmCRcGBLW2OfllQ,iv:Ga81hsKNfCkS+Y2ol6w00ICsn0EHSAs+/NSfQqjw2KA=,tag:Q0J8BU7KcHY0HhPsDKwggw==,type:str]
        OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:xBoWqr6XScJPq8h+ZvtDlmY9YKFbr64Q/MMtjuw2GqFC4alfsFg+som6IQlPBOCnqtxkXkJWxgZXbFaUdtr6EA==,iv:hybWMtLA+jGrQXlaLvVN3+2+BzdkwCW/uftRDxdQSlk=,tag:4CxTzBHT2nHKvAWfxHx9Cw==,type:str]
      type: ENC[AES256_GCM,data:2AxwlNYU,iv:nV4NM06Z6mqwTdI/z60x9/eNslQlTD5N4tWi2ZKzx40=,tag:r/jY/hTkJ6LSDE583N3NHg==,type:str]
