apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: karakeep-sso-secret
  namespace: karakeep
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQmd3eXlnODFDcGtUbHFZ
        WEVpbmNxZy84TStIVEZjSDEzaWtOU2pTWEJRCkxQbGxHN2NpaU82TVFBQUZqZWlw
        bzE1ZFBSelFVTVd3RDEwUWZDazhLVW8KLS0tIHkxcFZsSUdtN0xXcWhOTk94ejRy
        eHFPY3ZxYzZGNnF6MnByR2ptalBiWFEK2tZ4bWJLp4CSbeS1CbChuBmWeMIdu7ZS
        qsKgbdwU24pITxAxdWT8ADxQF5a5LcgrtAKezRJoyTxzfgWExwoA+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-08T14:47:27Z"
  mac: ENC[AES256_GCM,data:ej0MpZR6FvMT+ScrLIP2whOs8ZfAcVW10hLKIsMhQTVFHFLJ7un3WXkL2tjMuPJ1qbzZa6TwMGqn5dteHVljY1hchDcxbg6vmA9qEyQMSy4WuGF83IXrUrXl6KmleXSJg6dOR4iTAo4tthO9IWEV9BvKJvQTzumj/1u2O1tUQfQ=,iv:GgTykGNZSmPKTlvHNYCmi9EIu4b57jSiAaSQqBCvilY=,tag:f5RAzlCeNX5DZe6+nPZdHQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:ewSvR1GEE71vYPJmnnuG2Yyb8Q==,iv:0D+kWIbJ1P81hznpd1b8EyvqLKTmnTm7Mo6uK2eka9c=,tag:+PJeLXK8KE2JhdO84c/xvg==,type:str]
      stringData:
        OAUTH_CLIENT_ID: ENC[AES256_GCM,data:uW1a+v0XHgZz+sBWTnI/dbktSIU/VJ6qbmmpTSCurjY=,iv:OyF0zjx4AwDLgdXJK3CvJEDB6AW+6AZswla1EkfeSGs=,tag:0XDJQLEFavWQ20kmcLEvOQ==,type:str]
        OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:at3/8xn2pFl9SQcamHnH5foBevh0GSkilunL02DZasYODehqoYhaRcVLu3Haf6qkfnjq1aj+UYr4GmRgBPaXHqJ6pJqCvtKKThkP72dUe8YuawX/YmijMYQFwRGrp1CnQmLi5zbsUCcCd8XtC+1jz76Z0sfzxwBLSTluj7OVMKz11u9nGSe8vpVipGM8WPH2QIcp6HmTYBQqMuJoaMw846drbKc5iswfGmrDeTk6zAKDtSxdHoA6YhYQeCxGyhwvsGErSxsi/1rXQLYSlsHhoVDXAS/UlsfIFNqago2weCKqTxGAZIPT5uV+KiAP2Nqf7pzP9yTlcqqff11wCzgjP9EDRAfJGWMtiXnwhn5QZOIYflJAnDA9FbdvetfcOYDGBGkjFZhQvO+3saSiZEHN1RMkRDt5VEGmuq3ePbEiJdbQ1ullT26OWb6eX9EGyTYH9fzqTNU0ir6Lmj/nNAoqIUKy0k/K9Y9ecFTINd7TwKMwoSc7xeTTYlU+R8qsxhBkc5IInZNLnWNmwhyvJ38dqbE7MK2gPp3XGsu7EvYFa1qgt8Si6XGLUGcsvQPJcekIVRF1Zx6bT8ZpPEfkINFZxOCeGgTqJCMnr0kiPtB3XaaOFVkO6Y7+3QTb7TqkX0sgdy22UQ3d1moUcQNpbvGKboXj9SR+XmKRDhbh78qJ9fCrULQ7UzalQlfTBrdn0SEvLKcQ5/u8iG8iCQ==,iv:x5kvQfF4GD5LLDAAXftDVe7tF1AyOpxZ6XSEjMPwHVU=,tag:mdvkRjL0Q4FZKHt7wc0uQA==,type:str]
      type: ENC[AES256_GCM,data:fhF/aaS9,iv:WNOcSCwgWdBQXQIC+9/0UVxdnhN+hWViDt4tkaixcJ8=,tag:xdcHP6b9WDpgHpwRKr26Tg==,type:str]
