apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: reflector
    app.kubernetes.io/version: 10.0.8
    helm.sh/chart: reflector-10.0.8
  name: reflector
  namespace: reflector
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - watch
      - list
