apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: reflector
    app.kubernetes.io/version: 10.0.14
    helm.sh/chart: reflector-10.0.14
  name: reflector
  namespace: reflector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reflector
subjects:
  - kind: ServiceAccount
    name: reflector
    namespace: reflector
