apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: reflector
    app.kubernetes.io/version: 10.0.30
    helm.sh/chart: reflector-10.0.30
  name: reflector
  namespace: reflector
