apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: barman-s3-secret-key
  namespace: reflector
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4elVEVkh6TFBiMWVkTGZR
        UlgydVpyVnBOWDZlTDMwb1QycW9JNmlGNW53CnBCaU5FM0tKQmY2ZkhUMHNsSGVT
        SXdkeFRnTmJvR3N0Qjg5RHVsbjN3YkEKLS0tIFdwczJham9rWFVMSUFLRExLeFh1
        YjVnR2Z4ZEhpRUNqYWcwSC9MdGNORDAKZOn3+jjMJRFMI1LxiDaEadn58T6xbIs4
        DgG4DOj7P8RHWmBQg1umIYmFWXmgbEBG6WqDDziJde9bLRUkns2uMA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-02-12T16:32:51Z"
  mac: ENC[AES256_GCM,data:xOJ4wb+uA6e4cq10jMYX+p4wdU2yE4rj/H0ZSad8iiiugGtidhSj0mfZV6ekEU0G1wfSex/p8n2HRfrlDzFrRm0COy7OEiD5EmoX/TBPHZInJ+KFY8EvbKpLFDZkSPEfBDKMra7XE0mR0fOOZbUnIGCMbfdp9NFFK2SKQciJakI=,iv:XmVkZADI7FwaFCzRT6eMexmBXDHh2rVuVJJf89KpOuA=,tag:m5c9ZR8prc/memvv+pWTcQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: ENC[AES256_GCM,data:3qjh+A==,iv:MauxBVdawxqlCjAJWNHqT1Fgm4R/FW2Y2osSdFPLNnM=,tag:1WNnBlGDVESBGy7pSMFQUA==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ENC[AES256_GCM,data:WSc3RR5/XDVjoaWQGfNOZYsSDhXUG9UvW9TfUDaNvA6DM+MmQhA0TqZ/jBj41cJVBDYoxLjBKQ==,iv:qYjW1np6JbO8d/O5taivzegYnkkCTQ6Jp9arkK5nkGw=,tag:eQ12tkFVw7mVv+IVkFC9jg==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: ENC[AES256_GCM,data:ckrF+g==,iv:fSrosTjGUS3IizkzYgL5R/MA1JPZ+5CHJcNItgXkj4o=,tag:l9b5PBD6J4SLyA7y1Voy0Q==,type:str]
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ENC[AES256_GCM,data:iTmG28oLC8fG3obu5l/s8o/m/oWJnfjPoGitmDgCRM1UX1z91D1yatYbk26SN+zc8z2s6dMAjg==,iv:yxRBEAgtht/7bGjHTwkxuE/Z1OC6si8ZPRDeUFZfm5U=,tag:mfYcnm2ifoLHnq2cvFEKxA==,type:str]
      labels:
        cnpg.io/reload: ENC[AES256_GCM,data:LfBEqQ==,iv:k4gy10C15wa83DLz2X1pqbm2gAH7+HTS+dGR4Ixz8ic=,tag:+zLoH4NduC6HssuS6akXMg==,type:str]
      name: ENC[AES256_GCM,data:sKzhIhln13/guLPhGv9fFeZN0Cg=,iv:rNpH07/R4ND7FU522I0v7EbYZobQWRAHwkt+B/sEE5s=,tag:s3qUucnxAN3FbMR2siJjbg==,type:str]
      stringData:
        ACCESS_KEY_ID: ENC[AES256_GCM,data:8NEFYqH7Jr9M0oYvhVaH4+UESP9g/5PJrlE=,iv:fRYw+mAgf+ToHVapjVd6Js1Ik3a1mrkQyiXitEUHlNY=,tag:KI4Gt3qRWiiZnjqeqb+PFg==,type:str]
        ACCESS_SECRET_KEY: ENC[AES256_GCM,data:XYVBohFe1BgWoEYB//NznPAuTSYmHtB2cRSiPUh4bgSsBMGVXeNJeZlOeAlPhbWm8eGHox0WGjxZSs0Y2IUwuw==,iv:8yJm2+W+3oitEL+area5cyssbCAMVziytZH0Idli+6A=,tag:n/Tzoc6tudlcgbdPwcCceQ==,type:str]
      type: ENC[AES256_GCM,data:sclep5Nu,iv:FGjWJLiNVOPl9u48kDU2wmR/xxcnjDzjOSBZL4SV02s=,tag:DzGuRw+jPD20AWcF/8iJ7g==,type:str]
