{
  charts,
  lib,
  config,
  ...
}: let
  namespace = "ncps";
  domain = config.noosphere.domain;
  # The CNPG template names the cluster `pg-${instance}`, so derive the name
  # rather than writing it out twice — the two drifted apart once already.
  db-cluster-instance = "ncps-rev1";
  db-cluster-name = "pg-${db-cluster-instance}";
  objectStoreName = "ncps-object-store";
  signingKeySecret = "ncps-signing-key";
in {
  imports = [
    ../../../_modules/templates/database-template.nix
    ../../../_modules/templates/garage-object-store.nix
  ];

  applications.ncps = {
    inherit namespace;
    createNamespace = true;

    yamls = [
      (builtins.readFile ../../../../../../../vars/shared/${signingKeySecret}/${signingKeySecret}/value)
    ];

    # CNPG backups and WAL archiving for the cluster below. Without this the
    # `barman-cloud.cloudnative-pg.io` plugin has no ObjectStore to write to,
    # WAL is never recycled and the WAL volume fills until Postgres won't start.
    templates.garageObjectStore.${objectStoreName} = {
      inherit namespace;
      awsDefaultRegion = "backup";
      destinationPath = "s3://ncps-backup/backups";
      endpointUrl = "http://garage-backup.garage-operator.svc.cluster.local:3900";
      S3Credentials = {
        accessKeyId = {
          name = "ncps-backup-s3-secret-key";
          key = "MINIO_ACCESS_KEY_ID";
        };
        secretAccessKey = {
          name = "ncps-backup-s3-secret-key";
          key = "MINIO_SECRET_ACCESS_KEY";
        };
      };
    };

    helm.releases.ncps = {
      chart = charts.kalbasit.ncps;

      values = {
        replicaCount = 1;
        mode = "statefulset";

        config = {
          upstream.caches = [
            {
              url = "https://cache.nixos.org";
              publicKey = "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=";
            }

            {
              url = "https://nix-community.cachix.org";
              publicKey = "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=";
            }

            {
              url = "https://nix-gaming.cachix.org";
              publicKey = "nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4=";
            }

            {
              url = "https://devenv.cachix.org";
              publicKey = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
            }
          ];

          hostname = "ncps.${domain}";
          server.addr = ":8501";
          signing = {
            # Minted by the `ncps-signing-key` clan var (see
            # rke2/kube-secrets/ncps) rather than auto-generated by ncps, so the
            # public key clients trust is stable across a rebuild of this app.
            # The chart requires the data key to be named `signing-key`.
            existingSecret = signingKeySecret;
          };

          cache.maxSize = "250G";

          storage = {
            type = "s3";
            s3 = {
              bucket = "ncps";
              endpoint = "http://garage-s3-api.garage-operator.svc.cluster.local:3900";
              region = "main";
              # Garage only serves path-style addressing on the plain service
              # endpoint; the chart defaults this to false (AWS vhost style).
              forcePathStyle = true;
              # Created by resources.garageKeys.ncps in the garage-operator app
              # and mirrored into this namespace by reflector. Supplies the
              # access-key-id / secret-access-key keys the chart expects.
              existingSecret = "ncps-s3-secret-key";
            };
          };

          database = {
            type = "postgresql";
            postgresql = {
              # `existingSecret` is deliberately left unset. The chart hardcodes
              # the key it reads out of that secret (`database-url`, see
              # `ncps.cacheDatabaseURLEnv` in the chart's _helpers.tpl), while
              # CNPG publishes the connection string under `uri` in
              # ${db-cluster-name}-app. Neither side can rename its key, so the
              # URL is injected by overriding CACHE_DATABASE_URL on the workloads
              # below instead. The settings here only feed the chart-managed
              # secret that the override makes redundant; they are filled in so
              # the rendered config still describes the real target.
              host = "${db-cluster-name}-rw.${namespace}.svc.cluster.local";
              port = 5432;
              database = "app";
              username = "app";
              sslMode = "require";
            };
          };

          redis = {
            enabled = false;
          };

          observability.opentelemetry = {
            enabled = true;
          };
        };

        # `service` and `ingress` are top-level chart values, NOT part of
        # `config` — nesting them under it renders no Ingress at all.
        service = {
          type = "ClusterIP";
          port = 8501;
          portName = "http";
          annotations = {};
        };

        ingress = {
          enabled = true;
          className = "traefik";
          annotations = {
            "cert-manager.io/cluster-issuer" = "letsencrypt-cloudflare";
            "glance/name" = "Ncps";
            "glance/icon" = "di:nixos";
            "glance/url" = "https://ncps.${domain}";
            "glance/description" = "Nix Binary Cache";
            "glance/id" = "ncps";
            "glance/parent" = "ncps";
            "category" = "storage";
          };

          hosts = [
            {
              host = "ncps.${domain}";
              paths = [
                {
                  path = "/";
                  pathType = "Prefix";
                }
              ];
            }
          ];

          tls = [
            {
              secretName = "ncps-tls";
              hosts = ["ncps.${domain}"];
            }
          ];
        };
      };
    };

    # The chart only ever reads the connection string from CACHE_DATABASE_URL,
    # so pointing that env at CNPG's generated secret is enough — no chart
    # `existingSecret` is involved. `migration.mode` defaults to
    # "initContainer", so the init container needs the same value; if fsck or
    # the migrate-*-job hooks are ever enabled, they need it too.
    resources.statefulSets.ncps.spec.template.spec = let
      # mkForce because the chart already defines CACHE_DATABASE_URL (pointing
      # at its own secret's `database-url` key); without it the two definitions
      # conflict rather than the override winning.
      databaseURL = lib.mkForce {
        valueFrom.secretKeyRef = {
          name = "${db-cluster-name}-app";
          key = "uri";
        };
      };
    in {
      containers.ncps.env.CACHE_DATABASE_URL = databaseURL;
      # The migration init container reads DATABASE_URL on v0.9.4; upstream has
      # since renamed it to CACHE_DATABASE_URL to match the
      # --cache-database-url flag. Set both so this survives the chart bump —
      # whichever one the image ignores is just an unused env var.
      initContainers.migration.env = {
        DATABASE_URL = databaseURL;
        CACHE_DATABASE_URL = databaseURL;
      };
    };

    templates.cnpg-database-cluster.${db-cluster-instance} = {
      inherit namespace;
      overrideObjectStore = objectStoreName;

      cluster = {
        annotations = {
          "argocd.argoproj.io/sync-options" = "Prune=false,Delete=false";
          "argocd.argoproj.io/sync-hook" = "PreSync";
        };

        spec = {
          imageName = "ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie";
          storage.size = "10Gi";
          walStorage.size = "10Gi";
          plugins = [
            {
              isWALArchiver = true;
              parameters.barmanObjectName = objectStoreName;
            }
          ];
        };
      };

      # Ncps uses the default database created with the cluster
      databases = [];

      backups = {
        scheduledBackups = [
          {
            metadata.namespace = namespace;
            spec = {
              schedule = "0 2 0 * * *"; # Backup at 2AM every night
              backupOwnerReference = "self";
              immediate = true;
            };
          }
        ];

        onDemandBackups = [
          {
            spec = {};
          }
        ];
      };
    };
  };
}
