apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      type: LoadBalancer
      annotations:
        metallb.io/allow-shared-ip: "noosphere"
        metallb.io/loadBalancerIPs: "192.168.1.240"

    providers:
      kubernetesGateway:
        enabled: true
