apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-forgejo-on-demand-backup-0
  namespace: forgejo
spec:
  cluster:
    name: pg-forgejo
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
