apiVersion: v1
kind: Secret
metadata:
  labels:
    app: forgejo
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/version: 15.0.4
    helm.sh/chart: forgejo-17.1.2
    version: 15.0.4
  name: forgejo-inline-config
  namespace: forgejo
stringData:
  _generals_: |-
    APP_NAME=Imperial Forge
    RUN_MODE=prod
  cache: |-
    ADAPTER=memory
    HOST=
  database: |-
    DB_TYPE=postgres
    HOST=pg-forgejo-rw
  lfs: |-
    MINIO_BUCKET=forgejo-lfs
    MINIO_BUCKET_LOOKUP=auto
    MINIO_CHECKSUM_ALGORITHM=default
    MINIO_ENDPOINT=garage-s3-api.garage-operator.svc.cluster.local:3900
    MINIO_INSECURE_SKIP_VERIFY=false
    MINIO_LOCATION=main
    MINIO_USE_SSL=false
    SERVE_DIRECT=false
    STORAGE_TYPE=minio
  metrics: ENABLED=true
  oauth2: INVALIDATE_REFRESH_TOKENS=false
  queue: |-
    CONN_STR=
    TYPE=level
  repository: ROOT=/data/git/gitea-repositories
  security: INSTALL_LOCK=true
  server: |-
    APP_DATA_PATH=/data
    DOMAIN=forge.noosphere.uk
    ENABLE_PPROF=false
    HTTP_PORT=3000
    LFS_START_SERVER=true
    PROTOCOL=http
    ROOT_URL=https://forge.noosphere.uk
    SSH_DOMAIN=forge.noosphere.uk
    SSH_LISTEN_PORT=2222
    SSH_PORT=22
    START_SSH_SERVER=true
  session: |-
    PROVIDER=memory
    PROVIDER_CONFIG=
  storage: |-
    MINIO_BUCKET=forgejo
    MINIO_BUCKET_LOOKUP=auto
    MINIO_CHECKSUM_ALGORITHM=default
    MINIO_ENDPOINT=garage-s3-api.garage-operator.svc.cluster.local:3900
    MINIO_INSECURE_SKIP_VERIFY=false
    MINIO_LOCATION=main
    MINIO_USE_SSL=false
    SERVE_DIRECT=false
    STORAGE_TYPE=minio
type: Opaque
