apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: forgejo-s3-secret-key
  namespace: forgejo
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUzlxdVEvR3dJaVQzb1RT
        NU1tbTdGWDFBSk1hZGN1VGY1M2VEdGVTNEdvCjlUWGNzQUtncGRFOFVXakJDWDU1
        SXY1VVZUemNwNld6czhKUFlBVVM3UncKLS0tIGxybXpWNTFGTjhpMmRWNkp6Rity
        Yzk5cGZHOTRJMW01OUNsK0pXdkhseTQKrTt1+RD5jPR9PsRqqTVPIERdaLAbm2KB
        rQiaKXiJ1bE1iZklqTQJvONlrHiSkiDftrD/YPkeVAHqnkH1NySjBw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-02-11T19:19:46Z"
  mac: ENC[AES256_GCM,data:wAR3ULp1/73R7JtRSMaQLdg39qfxbJ7l+lEZqjTUvXmK6yxSTDnziDdTbOSZNNky979gcmBIX/p3VgnwjN+m4SDnx9nCw3aQM2promtPoDhy4VeVeyIJlSZjdTnZEnP65dy/8LrQFtUCYb0HT+TJ7SHTu0QJmeoaCuUKWJ19lho=,iv:UC0mHeevWJVYUg9zUdr1UGjKQSLzyqWIJzQCOkMEVBc=,tag:4PChtUASOX3MFI8yzq1RCw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:6y51ja5wIS5af3Mdg6GPNnY5LTCW,iv:V3prHmP1Lk55IqV4hcCKoNalX4rLXc4USJ0npJhWFY0=,tag:MpInR/dJKAF4xdU3bxzMcA==,type:str]
      stringData:
        MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:jG27N/hGlWJxxI5xAM+at5dtMFjoRJ/B43U=,iv:x+lEPt30KN2xc6K4xuZu3Wt+2i41JUzHQ3UvwN2ifh4=,tag:mN5KjzhLtffwFIyqGVsf8g==,type:str]
        MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PpLtnImWTrmKRMk1fdte9h0P1Pnr10g0xBuL90ow9Ka2B0QA4NHmNhvT7Imb4XC1rL7I50tpCfd1rDYzRSYqrg==,iv:0acQooRZ90TSoxMR+dhfj/vSuiNN6zG/MRWh8917AE8=,tag:T9cs5ehTPy1bF0sBxaRlPg==,type:str]
      type: ENC[AES256_GCM,data:iR2fB35M,iv:lkH8EbCG8S6RbHoLT0r4WKUjB6wC5wPwCbEvJwVZxvM=,tag:aDB3l/4m5IXLXEQRfulHrw==,type:str]
