apiVersion: v1
data:
  database-url: cG9zdGdyZXNxbDovL2FwcEBwZy1uY3BzLXJldjEtcncubmNwcy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2FwcD9zc2xtb2RlPXJlcXVpcmU=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: ncps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ncps
    app.kubernetes.io/version: v0.9.4
    helm.sh/chart: ncps-v0.9.4
  name: ncps
  namespace: ncps
type: Opaque
