apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ncps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ncps
    app.kubernetes.io/version: v0.10.0-rc18
    helm.sh/chart: ncps-v0.10.0-rc18
  name: ncps
  namespace: ncps
