apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: ncps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ncps
    app.kubernetes.io/version: v0.10.0-rc18
    helm.sh/chart: ncps-v0.10.0-rc18
  name: ncps
  namespace: ncps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: ncps
      app.kubernetes.io/name: ncps
  serviceName: ncps
  template:
    metadata:
      annotations:
        checksum/config: 61402d3d8a2243ccf71664344ec5baa376d13bb7a260af099f84d5e6451f07be
        checksum/secret: efc18bb980d59d18d1ed0c36fe13dbcd9242b063532d96ced2adc4af881b8ccf
        checksum/signing-key-secret: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
      labels:
        app.kubernetes.io/instance: ncps
        app.kubernetes.io/name: ncps
    spec:
      containers:
        - args:
            - --config
            - /etc/ncps/config.yaml
            - serve
            - --cache-secret-key-path
            - /etc/ncps/secrets/signing-key
          command:
            - /bin/ncps
          env:
            - name: CACHE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: pg-ncps-rev1-app
            - name: CACHE_STORAGE_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access-key-id
                  name: ncps-s3-secret-key
            - name: CACHE_STORAGE_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-access-key
                  name: ncps-s3-secret-key
          image: ghcr.io/kalbasit/ncps:v0.10.0-rc18
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: ncps
          ports:
            - containerPort: 8501
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/ncps/config.yaml
              name: config
              readOnly: true
              subPath: config.yaml
            - mountPath: /tmp/ncps
              name: tmp
            - mountPath: /etc/ncps/secrets/signing-key
              name: signing-key
              readOnly: true
              subPath: signing-key
      initContainers:
        - args:
            - migrate
            - up
          command:
            - /bin/ncps
          env:
            - name: CACHE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: pg-ncps-rev1-app
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: pg-ncps-rev1-app
          image: ghcr.io/kalbasit/ncps:v0.10.0-rc18
          imagePullPolicy: IfNotPresent
          name: migration
          resources: {}
          volumeMounts:
            - mountPath: /tmp/ncps
              name: tmp
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: ncps
      volumes:
        - configMap:
            name: ncps
          name: config
        - emptyDir: {}
          name: tmp
        - name: signing-key
          secret:
            secretName: ncps-signing-key
