apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-zitadel-backup
  namespace: zitadel
spec:
  cluster:
    name: pg-zitadel
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
