apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: percona-server-mongodb-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: psmdb-operator
    app.kubernetes.io/version: 1.21.2
    helm.sh/chart: psmdb-operator-1.21.3
  name: service-account-percona-server-mongodb-operator-psmdb-operator
  namespace: percona-mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: percona-server-mongodb-operator-psmdb-operator
subjects:
  - kind: ServiceAccount
    name: percona-server-mongodb-operator-psmdb-operator
