apiVersion: v1
data:
  config.yml: |
    service:
      publicurl: "https://vikunja.noosphere.uk"
    auth:
      openid:
        providers:
          pocketid:
            usernamefallback: true
            emailfallback: true
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/version: 2.6.0
    helm.sh/chart: vikunja-2.3.0
  name: vikunja-config
  namespace: vikunja
