apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: vikunja
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: vikunja-v2.0.2
  name: vikunja-data
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
