apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: pg-sonarr-password
  namespace: yarr
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RytmQVpVQVJyUlA0N3dk
        UXEycW9EMEZYNStWNkxDQXphUmt6c2dYZENvCk1IU2dIWWl6NzdkWTFsU3ZHZHRK
        aDFCbCs1bXdRbWNHZXU0d2N2UGQvS2cKLS0tIE43U3V1ejh5K1h2Ym4yM0pkanZj
        bUZrUG43VnI2anZiOUxqUXp4Sjg5aVEKHqItjZ+u0BCRVGHBw9MbAduadfs4LMcL
        8+9kvp+ryHEMaq77DMMzkLojPajoxX2ddAYqSlgajq7HlL1xplH86Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-02-18T16:42:21Z"
  mac: ENC[AES256_GCM,data:PO28ZZ34rSiPtNXY0qsj30NZ5m63VtjaxTE9tV1EPF3ozkQ4FU1IVMZeLd2L4ZBFFieHpb2dxaP3eZ8Ab7eB6WpwbxYDIdRByIsrqMBTLzzmiitPe08ZZ4hDyTG3vy05+9O1DbbGiLXKqzd4BEuUEbb+x5qEXhWKEWt6/ICmWbc=,iv:aAdz34jGY4eZYdq06GvMixUAoFjrwvrK5ReP0WqJBhs=,tag:+4EF8VSfpLvFmhGuDsXApg==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - labels:
        cnpg.io/reload: ENC[AES256_GCM,data:NTGzdw==,iv:jNjHmdTKdJ04yftCAPw1Hl5nSLf8XeONFukBmMoVj3s=,tag:TViSxU8BIfSCsnW4gSsD1w==,type:str]
      name: ENC[AES256_GCM,data:qVQ/7pw/jIKpJZTVxVXXGFkO,iv:gCcZbykGLZn5bm1c/A+QpaRadyupkNlj+3+2xuKDf90=,tag:f0sgY7+5Dlh9GZs3aYlxNw==,type:str]
      stringData:
        password: ENC[AES256_GCM,data:E1hlWojiveEBxy+oFCY=,iv:/Ub8PdYjGAA38A75kBxDDsk55GVuSYevcKXVNECj7oQ=,tag:tyY+9WE3oBGtjMG4Cf5y7g==,type:str]
        username: ENC[AES256_GCM,data:WCqzVK0i,iv:SWNcvOxZD8YpM1t9o1fqu1Vq4SBJ9ClIHzs+RRbWKHU=,tag:DoHZE9oUsZ395Khdm0rA1A==,type:str]
      type: ENC[AES256_GCM,data:aQ3Q/4fG,iv:lxUKo/5GOtiPFVLdXAIR3nZlfUjSk74kiYSD3jpcy3I=,tag:dTtzY1uaOKU+OUuilyEemQ==,type:str]
