apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-crow-backup
  namespace: crow
spec:
  cluster:
    name: pg-crow
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
