apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    argocd.proj.io/sync-hook: PreSync
    argocd.proj.io/sync-options: Prune=false,Delete=false
  name: pg-crow
  namespace: crow
spec:
  instances: 3
  monitoring:
    enablePodMonitor: true
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: crow-object-store
  postgresql:
    parameters:
      log_statement: ddl
      max_connections: "200"
      shared_buffers: 1GB
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: longhorn-cnpg-strict-local
  walStorage:
    size: 1Gi
    storageClass: longhorn-cnpg-strict-local
