apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: crowci
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crow-server
    app.kubernetes.io/version: 5.1.0
    helm.sh/chart: crow-1.0.2
  name: crowci-agent
  namespace: crow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crowci-agent
subjects:
  - kind: ServiceAccount
    name: crowci-agent
    namespace: crow
