apiVersion: v1
data:
  CROW_AGENT_SECRET: TlFVQVhGMkNpODhGbGxoZ3ZBS2JUdjJhcXBqT0tlRk9lbTBpRU5TNzZuZDVqOEpqS2RFVkdnQ2pjazE0bE0yYQ==
kind: Secret
metadata:
  name: crow-default-agent-secret
  namespace: crow
type: Opaque
