apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: crow-default-agent-secret
  namespace: crow
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZEU2NmMvUUQ5RWFiKy9o
        Ym96UTE3TlA1d1g0OWMvdEhrRFZLWnpjd1RzCmFUT3daaUhEOFhBNVN6R3dIUERP
        bkVnTjlSM0J2ZTNuRTMwM1dWbXlEQUEKLS0tIHQ5Q3UrcmZlSUxSbW84bjNEYm9y
        QjVyb0R3RDNvcExxLzZTSlBVeEszR3MK6Gj+QxTwFXHo/3QEfchZNRWoI7jkjIzO
        A7vAV6jj+JnzXckToKsye+X1P+9KBDqaSOAebZ1szl7EYifY2QGT3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-09T14:58:05Z"
  mac: ENC[AES256_GCM,data:c8Vj6DlEbLtu4ElwH4RPXJYjfASdN0z3wIzZ0fVKqdsT27ehYhXy2T4L3WiRGjuTAN160EFatkPCgbBPAwRZPNxCNyb2ODY4R2Q5xzxAJWPO0nk1ooQtnPMN7MTCBYtHxWnQ684vmaL4c//qagbk3CFj5RzOqKoAEnSsaQjyo2A=,iv:RgHo5BxFP+9JokAUj1e+SlvsoiPKa1ddnpHUAZ3THnE=,tag:qhnSNwZb+y/CtXE+lZyxfw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:mcFJGoJP0QElASGRvXBtFsz+GGHgF34p6g==,iv:B2hG1ShGxYf6wW5xIOl/Xx1C6uSp/K9N3RBXSd2KeSQ=,tag:LWxck3vfKVl9oE/+UvmF2Q==,type:str]
      stringData:
        CROW_AGENT_SECRET: ENC[AES256_GCM,data:s1A95B9dPpI4w+k7svfkIdWa5Q0bbzVIZdZez+o3PKg=,iv:2RArVahVP5Ed7cCIL9mXYccxj0bOaV6JJod5Wd/L9L0=,tag:XPsoScK/79zd6VUtp29yug==,type:str]
        CROW_DEFAULT_AGENT_SECRET: ENC[AES256_GCM,data:BrwC1hM8U0uSlXCyseSTnjaLxRLQ22pzFWgcX/yJ4vk=,iv:fKvMLN5LryUxQPi9Ck3QuFFAZ+9A8DOUWpl5ibtEeVY=,tag:4SWK1byoSCzbTfbw5mZZow==,type:str]
      type: ENC[AES256_GCM,data:SUygt8Tp,iv:cYXXSWKgL6wfCElAf5hFW28ltGJOlBWftj6SYu70NZg=,tag:s3BNdxBpTkMhtasPqac1VA==,type:str]
