apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: crow-agent-secret
  namespace: crow
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWTVmVHhjYXZwaXdNUEpr
        cEdmV3BPNVZYTENtcU5kdXRCUnltQTdXZlJBClhMaHFVUHJGSWRmRkFvM3Nqckda
        SkRFRTU3VzZwNzQrYmNjWkN2Q2xVY3MKLS0tIDBDVktoRG9JemkyNFdIclhrVkZP
        cWNTVXo5S3BpRjVuU1JiT1pZYkNIRm8K1+7k8um7LEmfaNOFXX8wOFN5sroTnn3o
        EOyfbprvnkJmQg1HbihTYaTeVHOXwJz1Pch5i6YfmXDRiaGG/DqLWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-09T13:09:12Z"
  mac: ENC[AES256_GCM,data:aMR9vEh+YeUuumTC4rQrjAPXCwG2X+kJwreBKu/+tmTlrmsYXlAWAnWx/r0KcDGOCXtDqEPj1E/w7ejoXvFmGnai8NOxWhIBUCbCgwGj8NEGCaY3Hb9Q7TxDVaVMTOenD+N8QJxD/aJ4YYmuR+SDEYCalMz8cOtMH+gVgLdOCL4=,iv:dIMbxilYChu4g9C9ZZf/v29ZOy4fM2qmxBEyV7q9OwI=,tag:aYMuPmav7O9ADDFTq2tQJA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:4NHy1iegZwHBhU4Wgmwp/lE=,iv:GKy1YHX3bE6qT9EqVdRpmxWNi//P5eWbFy5Foh96WfE=,tag:4II4PRWp829c3vcqzkAdsg==,type:str]
      stringData:
        CROW_AGENT_SECRET: ENC[AES256_GCM,data:I6lcFG8r5Tv0j1OSX4AL7PxcyT1tNDL4wcOrm1MBXKA=,iv:gm4JwJrcEHrzsDDFFQtIYsdTuwXhE0llU5xWugwhYZs=,tag:3Q9MGgu9IfpRs1kP/3dzdA==,type:str]
      type: ENC[AES256_GCM,data:4odw8DKc,iv:gsjh9q4X2wb9v1po1WS0khQKfMfsaouNz/24e8+48Jg=,tag:PZkkY9G5eznZ9AomA7i5Ow==,type:str]
