apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: crowci
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: crow-agent
    app.kubernetes.io/version: 5.1.0
    helm.sh/chart: crow-1.0.2
  name: crowci-agent
  namespace: crow
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: crowci
      app.kubernetes.io/name: crow-agent
  serviceName: crowci-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: crowci
        app.kubernetes.io/name: crow-agent
    spec:
      containers:
        - env:
            - name: CROW_SERVER
              value: crowci:9000
            - name: CROW_BACKEND_K8S_NAMESPACE
              value: crow
            - name: CROW_AGENT_SECRET
              value: ${CROW_AGENT_SECRET}
            - name: CROW_BACKEND
              value: kubernetes
            - name: CROW_BACKEND_K8S_POD_ANNOTATIONS
              value: ""
            - name: CROW_BACKEND_K8S_POD_LABELS
              value: ""
            - name: CROW_BACKEND_K8S_STORAGE_CLASS
              value: ""
            - name: CROW_BACKEND_K8S_STORAGE_RWX
              value: "true"
            - name: CROW_BACKEND_K8S_VOLUME_SIZE
              value: 2Gi
            - name: CROW_CONNECT_RETRY_COUNT
              value: "1"
          envFrom:
            - secretRef:
                name: crow-default-agent-secret
            - secretRef:
                name: crow-agent-secret
          image: codeberg.org/crowci/crow-agent:v5.1.0
          imagePullPolicy: IfNotPresent
          name: crow
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources: {}
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /etc/crow
              name: agent-config
      initContainers:
        - args:
            - |
              echo "Waiting for server pod to be healthy..."
              while ! curl -s http://crowci:80/api/healthcheck > /dev/null; do
                echo "Server not ready yet, waiting 5 seconds..."
                sleep 5
              done
              echo "Server is healthy, starting agent..."
          command:
            - sh
            - -c
          image: curlimages/curl:latest
          name: wait-for-server
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
      securityContext:
        fsGroup: 1000
      serviceAccountName: crowci-agent
  volumeClaimTemplates:
    - metadata:
        name: agent-config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
