apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-woodpecker-backup
  namespace: woodpecker
spec:
  cluster:
    name: pg-woodpecker
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
