apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: woodpecker-forgejo-oauth-secret
  namespace: woodpecker
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ2JYUkNuMFhMQlh2a096
        Y2JQT3JZMXltQ0NMSUtHcllmbkgydHNVVUEwCktBdUNhcVRzZGJwd2dXaDJuT1lX
        UzR3YWdsTXdvMjc3dW5xZ2FQVVNWZlEKLS0tIFpnU01CbXc2d2NCa2FnMG5JQTZn
        Z0czS3hSRnBScERBamJJQzYyUVJCb0EKObqdKAa8TciLHj+qNpMt9ZaippNB13t4
        PkhqcW6TcE6uU7C5vOldEjO2p5GdbGFl5GL7hPqrgQipBWq4+qxxEg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-09T17:18:14Z"
  mac: ENC[AES256_GCM,data:gMLTJDdxSXe+GK4RluaMGRd4vTagEgSLNvBlg3C1XLSddgNrfYNLZOCaw1tMv8ZHkdEPkPGQ7gtrskxdsh9F06eRhhz/M1/bCHoIYufDwBZ3cFs+u9G11UMoeb3K09lBbgGb/OGjfZcNCqJ8QCXC5B4bDzJRCqjaKAxxrIDuZak=,iv:C4QY29C6ZacPQIpkXP87mD14ac3WGdZUYkmbUl/r8R4=,tag:41zuR3SuSF6UhI98QVYjNA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:qkQlX6XzcJtupgWg1YyTqMf1hbpfxms2JiiG8OZp+Q==,iv:Jqvopb/C2PzBCFoU4M7UlPXMZP3i7FT5ZmJGaGS/3Ws=,tag:erylzQDuyrry32eWqjs4SQ==,type:str]
      stringData:
        WOODPECKER_CLIENT_ID: ENC[AES256_GCM,data:fDnv+2otOYUTCX8Y0Us52EcL1XNLxMAJT8Z81pjD2MTj053g,iv:zlGvxQQlyj8qxVNnRR8JxHrKhQbGEA725CPpU1b3YtQ=,tag:B/X77dYMkk4qfDbzk4yZPQ==,type:str]
        WOODPECKER_CLIENT_SECRET: ENC[AES256_GCM,data:/MLRHwwTbPmEBJqHQzTeIXLzSaHseDMFyAQ10gkVx4JEv3oSYu7+1f4bxh5frK+sPfB8Cnfv8+Y=,iv:ml+Uqu19JginoStFd3rSFUe2+tBkkKMHVPAxPXEykq8=,tag:DwDSaZM4oZ7VM1uM0r4dMQ==,type:str]
      type: ENC[AES256_GCM,data:K7ZncYMj,iv:X7alHxe3XswOokBfDyBD+64QZLn58rq2Hz4KpgGalL8=,tag:kkQ/Hu1vR4ALCqfPtTAaeA==,type:str]
