apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: woodpecker-default-agent-secret
  namespace: woodpecker
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MWc2cC9xYUI2THNjVGdD
        NEZETjhCSzkrcGJNL3RjcFJtS0l0Ty83MWdRCkg3cU90OTgzTE9OcTBGMzlwRFRu
        ZXAxR1c0Slk5akNHblBrNlVaRGRqL1kKLS0tIEF0NTV2MnRNb1VjZXhqdFo5eUJI
        YkF5Z2l1MGdlKzBWWVg4QUlIWEF6dlEKtqT9bUyPIH7bnovNx1JFDsBvE3XITsB5
        yuk0nYGQcIRVLiqCyUs9Yy5XFJqEnvfb06MxH1zX9ugwB2b/YRl6Xg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-09T16:57:19Z"
  mac: ENC[AES256_GCM,data:Lc1JILNcNgaQM2OmGvO7Vu2mg5lS2/c7QmgXcV3u8kbQfQmcD0LdbxcTQ33UzrJnZ0BlAA2u8fdyErV3iFuYr7y0zN01waAEcGj8r+3MkawA23ILBEKhHgFRLXFvnQTTKVYIuPHaEpUe+JdQGvs1ymTw1RXW7K/IxFMCyKkiqY0=,iv:LlYqskDPBBIlodmTiJ/uH8qv3NxRBvEGpZphTRrVvEM=,tag:MyPbzgPP4qISyYkEh1dLxA==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:mFkRI4x7XYfgiJekumyDuyeuaD895fGXIbzd7HdYMw==,iv:LGAaJM7HVSe11sXOtMdnAeNArgQ+VnZPbqxHxkaQm0w=,tag:C2oOuUJpVnVNggIx4tKzZQ==,type:str]
      stringData:
        WOODPECKER_DEFAULT_AGENT_SECRET: ENC[AES256_GCM,data:ylnAIC9w4jOn1y6YInhNFDjvnFaLcgVsDqfKnu002yFJk8v0AoTuA9iQN17l4/itBf/Tgz1Hg1Pplf8ongRP6w==,iv:j+nWpEYSQvJgauBatjJgOEdZjohLUQfgwfTVPqFAKe8=,tag:Kp7faFYdW2U2yIdfiVcBXg==,type:str]
      type: ENC[AES256_GCM,data:pjY0YVXC,iv:qXJGIatm9b3laAuzXcPeN/YtNaZOMasVdLksBbniFlw=,tag:U3WIevxzL9T73fUqkpefwg==,type:str]
