apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: woodpecker-agent-secret
  namespace: woodpecker
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzd0pOKzE1blA4NmNMUXlp
        MnR5UldvWlV3cUZlUEdDVjNTaVNuZzRmTURRCm5sY0xVNEVISXdYMFh3TE5POTZG
        M0FKTDF2eXlwVU5MdkdIY3NEYXJuUDQKLS0tIHhSSGJxVWJDZVpxSTlBL1VkNjZC
        d0tQczlJUW5lRDlHWjlTcGw5MDhoRXMKPzraGEsue/J2zCh2UR5tjtUdG8QhBGMp
        v9rxB0wAeFa4VJ6n72gj//tgGgcE/9EZE2ptN7ktfg+toPrFl8UTsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-09T16:02:29Z"
  mac: ENC[AES256_GCM,data:mdLI9muNOsxIygat8vMJqpRTbzPU8eesT6Ok0qrwNK/SQ+VmC1zMf5Ob5mXJMSbm+eCRYITZVkHvjwKb0PQ2C2kDgSApZ74hE1r+eQoVLPLHmuKhGV4ADfil09NU8udDKf2rp+0ysRCr9WL/KZOJUfMHjv+tEmuqmjEPTfAoN+A=,iv:9WE4BtU0NVGGL795bKRNBYR7wRRvRrhgcS7F6lL/OLE=,tag:EMvZhEw7eh9ieW4Em1OYIQ==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:21L7FDwsTm+RcAGK63+zbAiuQa1QkLY=,iv:dC5axBfgt0sAITKzNJklIwI/LjxZCydqewmqYLV6t9o=,tag:pCf2rO3zx7M8Wo5z1RNYWA==,type:str]
      stringData:
        agentSecret: ENC[AES256_GCM,data:CchdLGOq70rPA4C9KwKSTNR4Ms8Qz9P1Kt3EGLr8yf2pFe2D7ePhUgBAGddD47/Ja5GTHpumSs3BcTv/C4ohmg==,iv:iuIC1CuzAXs/ROm4jaXIb8Pcm5Hdchrx5QzP5kwPmY0=,tag:bfKx+cJS9MRQ8XYWhmNP3Q==,type:str]
      type: ENC[AES256_GCM,data:u74JnLIM,iv:JwR/i9EFmKgFmCzsxw+4WiAcQIrfqwLfSWBFOf8XJqw=,tag:eAU19s+Kn2RdVLhXvcF69g==,type:str]
