apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    category: storage
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    glance/description: Distributed S3 Storage (Main)
    glance/icon: di:garage
    glance/id: garage-main
    glance/name: Garage Main
    glance/parent: garage
    glance/url: https://ui.main.garage.noosphere.uk
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  name: garage-main-ui
  namespace: garage-operator
spec:
  ingressClassName: traefik
  rules:
    - host: ui.main.garage.noosphere.uk
      http:
        paths:
          - backend:
              service:
                name: garage-main-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ui.main.garage.noosphere.uk
      secretName: garage-main-ui-tls
