apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-harbor-on-demand-backup-0
  namespace: harbor
spec:
  cluster:
    name: pg-harbor
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
