apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    argocd.proj.io/hook: PreSync
    argocd.proj.io/sync-options: Prune=false,Delete=false
    argocd.proj.io/sync-wave: "-10"
  labels:
    release: kube-prometheus-stack
  name: pg-harbor
  namespace: harbor
spec:
  instances: 3
  managed:
    roles:
      - comment: Harbor User
        ensure: present
        login: true
        name: harbor
        passwordSecret:
          name: pg-harbor-postgres-secret
        superuser: false
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - action: replace
        sourceLabels:
          - cluster
        targetLabel: cnpg_cluster
    podMonitorRelabelings:
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_name
        targetLabel: pod
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: harbor-object-store
  postgresql:
    parameters:
      log_statement: ddl
      max_connections: "200"
      shared_buffers: 1GB
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: longhorn-cnpg-strict-local
  walStorage:
    size: 20Gi
    storageClass: longhorn-cnpg-strict-local
