apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: harbor-object-store
  namespace: harbor
spec:
  configuration:
    destinationPath: s3://cnpg-backup-bucket/backups
    endpointURL: http://garage.garage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: barman-s3-secret-key
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: barman-s3-secret-key
    wal:
      compression: gzip
  instanceSidecarConfiguration:
    env:
      - name: AWS_DEFAULT_REGION
        value: garage
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
