apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: harbor-oidc-config
  namespace: harbor
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTEZ0Y0hzSklncC85djlQ
        UjAvWU84TmNPbWxQNTBEQ1V1T05QYUFXd2dJCmpocXoyV0VqaWJ1YUdZbzJKeGdZ
        N0pYdUdTa0M1dVRGQjE3RExtNkFuQUkKLS0tIFo4L2ZzZmhOaE1Zck5NSFFxYUxR
        N0ExN2lqRTRzY0pGcWgwQ2MxMVEvdjQKWI76wTHSGV2v2rRYpqCoiHT/8YuMTDhE
        xu0jZNbquoBrgq0AzrWl5pmHDV0UJVTcWF+OExx1PpSOaZ4S0J3LJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1juzhlapy63msgtzzelusuqqq0hy24907eh0zd7xxzpkjtt5m053sv6a38g
  encrypted_suffix: Templates
  lastmodified: "2026-01-13T14:54:37Z"
  mac: ENC[AES256_GCM,data:W7OZKIS8waZfMULzjzZF3PMoD8P4X7RMM3Uvb19GGuQHW4tl8yQmBWqj28TPPnIx0lr7pt5q/9hTJMYbWntLIM5+Vy1+fCl4Y8HTuUE+XzHt77RHnVft1voUbol7xx0WptDVi5X7iuqJZtwE+M1G9Ilu9GsMPbuDCps71BDs1c0=,iv:6+Wnmohi4SesH+HTt4UI757gFx91FBlXRCtybQetyOw=,tag:Np4bP9E80Lni3uOcWZCxLw==,type:str]
  version: 3.11.0
spec:
  secretTemplates:
    - name: ENC[AES256_GCM,data:GNA7brRfJtbZ7uzAR17xwfxt,iv:1qiuKEbLjS7s6to4q11fc25Dm/31MKk+4gOg5dyTPhE=,tag:bstQC8WiJ252I3eas0rxdQ==,type:str]
      stringData:
        CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:qEsFyQiraZseAaNXZVyenDRRtmVZzfBdlDKv2PIHJMH+AwSbabyiC6QEHiyLc1w5rhnz7nVy8/TsfLzkL/9331Mjj3AyMomlVu6BtaEpCFhndWStMViQbT0Sz095+cbQ4DSkCWCAZHGZoB2FXwBasmv0qWaHAnA5IfQKrup+tAn5TVnyyTa9uD8qtwphgEI9KxYGzmBndeqprDBYNZJ7FF5o0R5hW8U71CkVhwK7aoqeg4Y3mDRCa4aBUSDI9Cnk5nmER/dTv1VyqoO5pHE36tcEFkGa6sayj81kz0WFxRY4yANWWv+7bprpZN+F6QfUnJaPov3CuPd+3j6r4HUHrjKHVXhlWfaDbsrvwwJrQrWvsG4n/aV/mjFkPhI0GdJQ2ZbQu1+q8IIDfuBNOmjHDICkhynzPwrMofd/w2iIuR6/h3atYB6Kkm7GhJg2W7y12dDoZwLOOTPp+tpUXM9Rpyg/mfHgBCvYH6LHVi9lwbsLUyJmefHmsLoGQvHSMFJh3aLU2+F5vmxPxvlqvSRJk6Tq,iv:+1Nm2nKhyJ00Q6C5ZFWxFyq5lSbmNvqLXED8THjt7d8=,tag:jGC5DeiOkDxgD4cGlgnibw==,type:str]
      type: ENC[AES256_GCM,data:wjTxsdCZ,iv:FB7rHMQ5ZOWP/4wmhOneoibiIv62JuJGJUxltSPCipE=,tag:huBgypPL8uRrv0xEcfVOBA==,type:str]
