apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-yarr-restored-backup
  namespace: yarr
spec:
  cluster:
    name: pg-yarr-restored
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
