apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: pg-yarr-backup
  namespace: cnpg-system
spec:
  cluster:
    name: pg-yarr
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
