apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    argocd.proj.io/sync-hook: PreSync
    argocd.proj.io/sync-options: Prune=false,Delete=false
  labels:
    release: kube-prometheus-stack
  name: pg-yarr-1
  namespace: yarr
spec:
  backup:
    retentionPolicy: 30d
    target: prefer-standby
  bootstrap:
    recovery:
      source: origin
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: yarr-object-store
          serverName: pg-yarr-restored
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-minimal-trixie
  instances: 3
  managed:
    roles:
      - comment: Seerr User
        ensure: present
        login: true
        name: seerr
        passwordSecret:
          name: pg-seerr-password
        superuser: false
      - comment: Prowlarr User
        ensure: present
        login: true
        name: prowlarr
        passwordSecret:
          name: pg-prowlarr-password
        superuser: false
      - comment: Sonarr User
        ensure: present
        login: true
        name: sonarr
        passwordSecret:
          name: pg-radarr-password
        superuser: false
      - comment: Radarr User
        ensure: present
        login: true
        name: radarr
        passwordSecret:
          name: pg-radarr-password
        superuser: false
  monitoring:
    customQueriesConfigMap:
      - key: queries
        name: cnpg-default-monitoring
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - action: replace
        sourceLabels:
          - cluster
        targetLabel: cnpg_cluster
    podMonitorRelabelings:
      - action: replace
        sourceLabels:
          - __meta_kubernetes_pod_name
        targetLabel: pod
  plugins:
    - isWALArchiver: true
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: yarr-object-store
  postgresql:
    parameters:
      log_statement: ddl
      max_connections: "200"
      shared_buffers: 1GB
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: longhorn-cnpg-strict-local
  walStorage:
    size: 1Gi
    storageClass: longhorn-cnpg-strict-local
