apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    argocd.proj.io/sync-options: Prune=false
  name: db-lidarr-logs
  namespace: yarr
spec:
  cluster:
    name: pg-yarr-1
  name: lidarr-logs
  owner: lidarr
