apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-yarr-restored-scheduled-backup-0
  namespace: yarr
spec:
  backupOwnerReference: self
  cluster:
    name: pg-yarr-restored
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: 0 2 0 * * *
